name: Delete abandoned branches

on:
  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
      - name: Get output
        run: |
          touch ~/temp-file
          ls ~
