# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'build'

        # The name of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_name: Mit Shah

        # The email of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_email: mits@mangospring.com

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'React Build'

